Repository UMC-TRIPY/web-front, pull requests merged in 2023-07, with the labels that each got.

#10 [FEAT] #8 - 헤더 및 푸터 구현
  public/images/logo1.svg
  public/images/logo2.svg
  src/app/layout.tsx
  src/components/layout/footer.tsx
  src/components/layout/header.tsx
Labels: FEAT

#15 [FEAT] #9 - 여행 정보 페이지 인기 여행지 및 추천 준비물 구현
  public/images/arrow.png
  public/images/prep1.png
  public/images/prep2.png
  public/images/prep3.png
  src/app/info/page.tsx
  src/components/hotplace/HotPlace.tsx
  src/components/infomenu/InfoMenus.tsx
  src/components/recoprep/RecoPrep.tsx
  tailwind.config.js
Labels: FEAT

#22 [DESIGN] #20 - 캘린더 CSS 작업
  package-lock.json
  package.json
  public/images/calendararrow.png
  src/app/globals.css
  src/components/infocity/InfoCity.tsx
Labels: DESIGN

#24 [FEAT] #13 - 마이페이지 기능 구현
  public/images/changePic.svg
  public/images/profilePicLg.svg
  src/app/mypage/page.tsx
  src/components/mypage/confirmBtns.tsx
  src/components/mypage/infoInput.tsx
  src/components/mypage/myInfo.tsx
  src/components/mypage/mypageMenus.tsx
  src/components/mypage/profilePic.tsx
Labels: FEAT

#27 [Feat] #23 - 환율 및 구글 지도 API 연동
  .gitignore
  package-lock.json
  package.json
  src/components/hotplace/HotPlace.tsx
  src/components/infocity/ExchangeRate.tsx
Labels: FEAT

#28 [FEAT] 구글 OAuth 구현
  src/app/auth/page.tsx
  src/app/page.tsx
  src/components/button/GoogleLoginButton.tsx
  src/components/community/Community.tsx
  src/components/community/Dropdown.tsx
  src/components/community/DropdownList.tsx
  src/components/conversation/ConversationItem.tsx
  src/components/conversation/ConversationList.tsx
  src/utils/google.ts
Labels: FEAT

#36 [FEAT] #26 - 마이페이지 친구관리창
  src/app/mypage/page.tsx
  src/components/layout/confirmBtn.tsx
  src/components/layout/roundBtn.tsx
  src/components/mypage/confirmBtns.tsx
  src/components/mypage/mypageMenus.tsx
  src/components/mypagefriend/follower.tsx
  src/components/mypagefriend/following.tsx
  src/components/mypagefriend/friend.tsx
  src/components/mypagefriend/friendReq.tsx
  src/components/mypagefriend/myFriends.tsx
  src/components/mypagefriend/sendFollow.tsx
  tailwind.config.js
Labels: FEAT

#39 [CHORE] #37 - 환율 API 재연동 및 일부 코드 수정
  src/components/detailschedule/FriendList.tsx
  src/components/hotplace/HotPlace.tsx
  src/components/infocity/Calendar.tsx
  src/components/infocity/ExchangeRate.tsx
  src/components/infocity/InfoCity.tsx
Labels: CHORE

#42 [FEAT] 일정등록 모달창
  postcss.config.js
  src/components/layout/header.tsx
  src/components/main/CardCarousel.tsx
  src/components/modal/LoginModal.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ScheduleAddModal.tsx
Labels: FEAT

#44 [FEAT] 일정 삭제 모달창 구현
  src/components/button/GoogleLoginButton.tsx
  src/components/button/KakaoLoginButton.tsx
  src/components/layout/header.tsx
  src/components/modal/LoginModal.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ScheduleDeleteModal.tsx
Labels: FEAT

#46 [FEAT] 일정 상세보기 모달창
  src/components/detailschedule/DetailSchedule.tsx
  src/components/detailschedule/FriendList.tsx
  src/components/detailschedule/LabelSchedules.tsx
  src/components/layout/header.tsx
  src/components/modal/ScheduleDetailModal.tsx
  tailwind.config.js
Labels: FEAT

#47 [DESIGN] 마이페이지 스크롤 디자인
  package-lock.json
  package.json
  src/app/globals.css
  src/components/mypagefriend/follower.tsx
  src/components/mypagefriend/following.tsx
  src/components/mypagefriend/friendOneBtn.tsx
  src/components/mypagefriend/friendTwoBtn.tsx
  src/components/mypagefriend/myFriends.tsx
  src/components/mypagefriend/sendFollow.tsx
  src/components/schedulemain/myTravel.tsx
  tailwind.config.js
Labels: DESIGN

#52 [FEAT] 여행 가방 페이지 구현
  src/app/mybag/page.tsx
  src/components/mybag/ListComp.tsx
  src/components/mybag/MyBag.tsx
Labels: FEAT

#54 [FEAT] 모달창 켜져있을 때 스크롤 막기
  src/components/modal/Modal.tsx
Labels: FEAT

#55 [FEAT] 새로운 가방 만들기 페이지
  public/images/bag.svg
  public/images/selectedBag.svg
  src/app/mybag/new/page.tsx
  src/components/detailschedule/CommonHeader.tsx
  src/components/detailschedule/OtherSchedule.tsx
  src/components/modal/NewBagModal.tsx
  src/components/mybag/BagList.tsx
  src/components/mybag/EmptyBag.tsx
  src/components/mybag/TopTab.tsx
Labels: FEAT

#56 [FEAT] 환율 api 수정 및 날씨 api 연동
  next.config.js
  src/app/info/page.tsx
  src/components/infocity/ExchangeRate.tsx
  src/components/infocity/InfoCity.tsx
  src/components/infocity/InfoWeather.tsx
Labels: FEAT
