Repository UMC-TRIPY/web-front, pull requests merged in 2023-08, with the labels that each got.

#64 [FEAT] 가방만들기 상세보기 모달
  src/components/detailschedule/LabelSchedules.tsx
  src/components/modal/BagpackingModal.tsx
  src/components/modal/MyBagModal.tsx
  src/components/mybag/DetailBag.tsx
  src/components/mybag/ListComp.tsx
Labels: FEAT

#63 [FEAT] 여행지 검색에 따른 정보 페이지 변경
  public/data/dummy.json
  public/images/centralpark.png
  public/images/disneyland.png
  public/images/dotonbori.png
  public/images/empirestatebuilding.png
  public/images/ghibliMuseum.png
  public/images/newyorkPic.png
  public/images/osakaPic.png
  public/images/osakajo.png
  public/images/shibuya.png
  public/images/statueofliberty.png
  public/images/timessquare.png
  public/images/tokyoPic.png
  public/images/tokyoTower.png
  public/images/umedaFloatingGarden.png
  public/images/universalStudio.png
  src/app/info/[city]/page.tsx
  src/app/info/page.tsx
  src/components/hotplace/HotPlace.tsx
  src/components/infocity/ExchangeRate.tsx
  src/components/infocity/InfoCity.tsx
  src/components/infocity/InfoWeather.tsx
  src/components/infomenu/InfoMenus.tsx
  tailwind.config.js
Labels: FEAT

#65 [FEAT] 여행가방 만들기 + 여행가방 디테일 페이지
  public/images/carrierHandle.svg
  src/app/auth/kakao/page.tsx
  src/app/mybag/detail/page.tsx
  src/app/mybag/new/page.tsx
  src/components/button/KakaoLoginButton.tsx
  src/components/layout/header.tsx
  src/components/modal/LoginModal.tsx
  src/components/modal/SearchboxModal.tsx
  src/components/mybag/BagDetail/CarrierSection.tsx
  src/components/mybag/BagDetail/MaterialSection.tsx
  src/components/mybag/BagDetail/MemoSection.tsx
  src/components/mybag/BagDetail/WeatherSection.tsx
  src/components/mybag/BagList.tsx
  src/components/mybag/DirectoryList.tsx
  src/components/mybag/ListComp.tsx
  src/components/schedulemain/detailBox.tsx
  tsconfig.json
Labels: FEAT

#70 [FIX] 구글맵 불러올 때 오류 발생
  src/components/hotplace/HotPlace.tsx
Labels: FIX

#74 [FIX] 타입 지정, 반복문 키값, 컴포넌트 이름 대문자 변경
  src/app/mypage/page.tsx
  src/app/schedulemain/page.tsx
  src/components/schedulemain/myTravel.tsx
  src/components/schedulemain/scheduleMain.tsx
Labels: FIX

#72 [FIX] 여행정보 메인페이지에서 검색했을 때 검색한 여행지로 페이지 이동
  package-lock.json
  package.json
  public/data/dummy.json
  src/app/info/[city]/page.tsx
  src/app/info/page.tsx
  src/components/hotplace/HotPlace.tsx
  src/components/infomenu/InfoMenus.tsx
  src/components/layout/header.tsx
  src/components/modal/SearchCityModal.tsx
Labels: FIX

#81 [FEAT] 가방 세부 페이지 준비물 추가하기
  src/components/mybag/BagDetail/CarrierSection.tsx
Labels: FEAT

#84 [FEAT] 가방 세부페이지 이벤트 연결
  src/app/mybag/detail/page.tsx
  src/components/mybag/BagDetail/CarrierSection.tsx
  src/components/mybag/BagDetail/MaterialSection.tsx
Labels: FIX, FEAT

#88 [FEAT] 가방 세부 페이지 수정하기 이벤트 연결
  src/app/mybag/detail/page.tsx
  src/components/mybag/BagDetail/CarrierSection.tsx
Labels: FEAT

#89 [CHORE] 검색 컴포넌트 분리
  src/app/info/page.tsx
  src/components/infomenu/InfoMenus.tsx
  src/components/modal/FixedSearchCityModal.tsx
  src/components/modal/SearchCityModal.tsx
Labels: CHORE

#92 [CHORE] API 인터페이스 생성
  src/apis/.gitkeep
  src/apis/material.ts
  src/apis/setting.ts
  src/apis/types.ts
  src/app/mybag/detail/page.tsx
  src/components/mybag/BagDetail/MaterialSection.tsx
Labels: CHORE

#95 [FEAT] auth API 인터페이스 구현
  src/apis/types.ts
  src/apis/user.ts
  src/app/auth/google/page.tsx
  src/app/auth/kakao/page.tsx
  src/components/button/KakaoLoginButton.tsx
  src/utils/oauth.ts
Labels: FEAT

#98 [FIX] 여행정보 메인페이지에서 검색어 선택했을 때 화면 밀리는 이슈
  src/components/modal/SearchboxModal.tsx
  src/components/modal/TransparentModal.tsx
  src/components/schedulemain/detailBox.tsx
  src/components/schedulemain/scheduleHeader.tsx
  src/components/schedulemain/scheduleMain.tsx
Labels: FIX

#106 [FEAT] 친구요청 API 연동
  next.config.js
  package-lock.json
  package.json
  src/apis/types.ts
  src/apis/user.ts
  src/apis/user/friend.ts
  src/apis/user/login.ts
  src/apis/user/types.ts
  src/app/RecoilProvider.tsx
  src/app/auth/google/page.tsx
  src/app/auth/kakao/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/components/layout/header.tsx
  src/components/mypage/infoInput.tsx
  src/components/mypage/myInfo.tsx
  src/components/mypage/mypageMenus.tsx
  src/components/mypagefriend/follower.tsx
  src/components/mypagefriend/following.tsx
  src/components/mypagefriend/friendTwoBtn.tsx
  src/components/mypagefriend/myFriends.tsx
  src/components/mypagefriend/sendFollow.tsx
  src/states/.gitkeep
  src/states/user.ts
  src/types/user.ts
Labels: FEAT

#109 [FEAT] 회원가입 퍼블리싱
  src/app/signup/page.tsx
  src/components/button/GoogleLoginButton.tsx
  src/components/button/KakaoLoginButton.tsx
  src/components/layout/header.tsx
  src/components/modal/LoginModal.tsx
  src/components/modal/LoginSignUpModal.tsx
  src/components/modal/SignUpDoneModal.tsx
  tailwind.config.js
Labels: FEAT

#110 [FEAT] 친구 API 연동
  src/apis/setting.ts
  src/apis/user/friend.ts
  src/apis/user/types.ts
  src/app/auth/kakao/page.tsx
  src/app/mypage/page.tsx
  src/components/layout/header.tsx
  src/components/mypage/myInfo.tsx
  src/components/mypagefriend/follower.tsx
  src/components/mypagefriend/following.tsx
  src/components/mypagefriend/friendOneBtn.tsx
  src/components/mypagefriend/friendReq.tsx
  src/components/mypagefriend/friendTwoBtn.tsx
  src/components/mypagefriend/myFriends.tsx
  src/components/mypagefriend/sendFollow.tsx
Labels: FEAT

#112 [FEAT] 로그아웃, 회원탈퇴 API 연동
  src/apis/user/login.ts
  src/components/layout/header.tsx
  src/components/mypage/confirmBtns.tsx
Labels: FEAT

#116 [FEAT] 회원정보 수정 API 연동
  src/apis/user/login.ts
  src/app/mypage/page.tsx
  src/components/layout/confirmBtn.tsx
  src/components/layout/header.tsx
  src/components/mypage/confirmBtns.tsx
  src/components/mypage/infoInput.tsx
  src/components/mypage/myInfo.tsx
  src/components/mypage/profilePic.tsx
Labels: FEAT

#115 [FEAT] 커뮤니티 글 작성 페이지
  package-lock.json
  public/images/alertCircle.svg
  public/images/alertCircleRed.svg
  public/images/calendar.svg
  public/images/folder.svg
  public/images/folderPlus.svg
  public/images/imageAdd.svg
  public/images/upload.svg
  src/app/community/write/page.tsx
  src/components/editorcommunity/editorCommunity.tsx
  src/components/editorcommunity/mainEditor.tsx
  src/components/editorcommunity/selectCountry.tsx
  src/components/editorcommunity/tagEditor.tsx
  src/components/modal/EditorModal.tsx
  src/components/schedulemain/myTravel.tsx
  src/components/schedulemain/scheduleMain.tsx
  tailwind.config.js
Labels: FEAT

#127 [FEAT] 구글 로그인 및 회원가입 로직 연결
  src/apis/types.ts
  src/apis/user/friend.ts
  src/apis/user/login.ts
  src/app/auth/google/page.tsx
  src/app/auth/kakao/page.tsx
  src/app/mypage/page.tsx
  src/app/signup/page.tsx
  src/components/mypage/infoInput.tsx
  src/states/user.ts
Labels: FEAT

#131 [FIX] 일정 상세보기 모달 추가, 페이지네이션 5페이지씩 쪼개기, 선택일정으로 일정 바꾸기
  src/app/info/page.tsx
  src/app/mybag/new/page.tsx
  src/app/newschedule/page.tsx
  src/app/summary/list/page.tsx
  src/app/updateschedule/page.tsx
  src/components/detailschedule/DetailSchedule.tsx
  src/components/detailschedule/LabelSchedules.tsx
  src/components/detailschedule/OtherSchedule.tsx
  src/components/maincommunity/Pagination.tsx
  src/components/modal/FixedSearchCityModal.tsx
  src/components/modal/ScheduleDetailModal.tsx
  src/components/modal/SearchCityModal.tsx
  src/components/modal/SelectScheduleModal.tsx
  src/components/mypage/MyBagList.tsx
  src/components/mypage/MyTravelList.tsx
  src/components/schedulemain/detailBox.tsx
  src/components/summary/CommonHeader.tsx
  src/components/summary/MyTravel.tsx
Labels: FIX

#136 [FEAT] 여행가방 API 연동
  src/apis/bag/index.ts
  src/apis/bag/types.ts
  src/apis/types.ts
  src/apis/user/friend.ts
  src/apis/user/login.ts
  src/app/mybag/detail/[bid]/page.tsx
  src/app/mybag/new/page.tsx
  src/app/mypage/page.tsx
  src/components/detailschedule/OtherSchedule.tsx
  src/components/modal/SelectScheduleModal.tsx
  src/components/mybag/BagDetail/CarrierSection.tsx
  src/components/mybag/BagDetail/MemoSection.tsx
  src/components/mybag/BagList.tsx
  src/components/mypage/confirmBtns.tsx
  src/states/schedule.ts
  src/types/bag.ts
  src/types/user.ts
Labels: FEAT

#141 [FEAT] 친구초대 및 일정에 초대된 친구 조회 연동
  src/apis/bag/index.ts
  src/apis/bag/types.ts
  src/apis/user/friend.ts
  src/apis/user/types.ts
  src/app/mybag/detail/[bid]/page.tsx
  src/app/mybag/new/page.tsx
  src/app/newschedule/page.tsx
  src/app/updateschedule/page.tsx
  src/components/conversation/Conversation.tsx
  src/components/detailschedule/DetailSchedule.tsx
  src/components/detailschedule/FriendList.tsx
  src/components/layout/header.tsx
  src/components/layout/roundBtn.tsx
  src/components/modal/FriendListModal.tsx
  src/components/modal/ScheduleListModal.tsx
  src/components/mybag/BagDetail/MaterialSection.tsx
  src/components/mybag/BagDetail/MemoSection.tsx
  src/components/mypagefriend/friendOneBtn.tsx
  src/components/mypagefriend/myFriends.tsx
  src/types/bag.ts
  src/types/user.ts
  src/utils/dateUtil.ts
Labels: FEAT

#143 [FEAT] 커뮤니티 기능 구현 및 관련 API 연동
  package-lock.json
  package.json
  public/images/eye.svg
  public/images/message-circle.svg
  public/images/thumbs-up.svg
  src/apis/community/posts.ts
  src/apis/community/update.ts
  src/app/community/view/[post_index]/page.tsx
  src/app/community/view/dummy/[keyword]/page.tsx
  src/components/countrycommunity/CountyPosts.tsx
  src/components/editorcommunity/editorCommunity.tsx
  src/components/editorcommunity/mainEditor.tsx
  src/components/editorcommunity/schedulePreviews.tsx
  src/components/editorcommunity/selectCountry.tsx
  src/components/editorcommunity/tagEditor.tsx
  src/components/maincommunity/AllPosts.tsx
  src/components/maincommunity/CommonHeader.tsx
  src/components/maincommunity/PostLists.tsx
  src/components/modal/EditorModal.tsx
  src/components/schedulemain/myTravel.tsx
  src/components/viewcommunity/comments.tsx
  src/components/viewcommunity/dummy/dummyContent.tsx
  src/components/viewcommunity/dummy/dummyHeader.tsx
  src/components/viewcommunity/viewComments.tsx
  src/components/viewcommunity/viewContent.tsx
  src/components/viewcommunity/viewHeader.tsx
Labels: FEAT

#147 [Fix] 여행 정보, 일정 관리 페이지 검색 기능 추가
  public/images/italy.png
  src/app/info/page.tsx
  src/app/page.tsx
  src/components/layout/header.tsx
  src/components/main/SearchCountries.tsx
  src/components/mypage/MyBagList.tsx
  src/components/mypage/MyTravelList.tsx
  src/components/schedulemain/SelectedPlaces.tsx
  src/components/schedulemain/detailBox.tsx
  src/components/schedulemain/hotSearch.tsx
  src/components/summary/MyTravel.tsx
Labels: FIX
